/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intellij;

public class App {

    public static void main(String[] args) {
        GoodClass myClass = new GoodClass("oh hey");
        System.out.println(myClass.modifyName());
        myClass.multiplesOfA(2);
    }
}
